server:
  port: 8080

eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka/

spring:
   application:
    name: Api-Geteway

   cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true

        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
            allowedHeaders:
              - "Origin"
              - "Content-Type"
              - "Accept"
              - "Authorization"
              - "User-Key"
              - "Request-Tracker"
              - "Session-Tracker"
              - "X-XSRF-TOKEN"
              - "X-IBM-CLIENT-ID"
              - "Message-ID"
              - "X-IBM-CLIENT-SECRET"
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_FIRST

      routes:
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/cart-service/**
          filters: AuthenticationFilter

        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/auth-service/**
          filters: AuthenticationFilter

        - id: restaurants-service
          uri: lb://restaurants-service
          predicates:
            - Path=/restaurants-service/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order-service/**
          filters: AuthenticationFilter

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
          filters: AuthenticationFilter
     
